name: CI de Pytest + Playwright

on: [push]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Ejecutar pruebas con Pytest
        run: |
          pytest --html=report.html

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-de-pruebas
          path: report.html
